"""Official strategy constants.

Keep this module declarative; signal, sizing, and execution behavior lives in
the strategy core engines.
"""

from __future__ import annotations


class StrategyConstants:
    VERSION_LABEL = "v1"

    TARGET_ALLOC = {
        "BTC/USDT": 1.0,
        "ETH/USDT": 1.0,
        "BNB/USDT": 1.0,
    }
    CONFIRM_BARS = {"BULL": 3, "MIXED": 5, "BEAR": 2}
    TARGET_TABLE = {
        "BULL": {0: 0.95, 1: 0.86, 2: 0.72, 3: 0.52, 4: 0.32, 5: 0.16},
        "RANGE": {0: 0.64, 1: 0.54, 2: 0.42, 3: 0.28, 4: 0.12, 5: 0.0},
        "TRANSITION": {0: 0.56, 1: 0.46, 2: 0.34, 3: 0.22, 4: 0.10, 5: 0.0},
        "BEAR": {0: 0.24, 1: 0.18, 2: 0.12, 3: 0.04, 4: 0.0, 5: 0.0},
    }
    CORE_FLOOR = {"BTC/USDT": 0.34, "ETH/USDT": 0.24, "BNB/USDT": 0.18}
    BTC_ADJUST = {"STRONG_BULL": 0.05, "BULL": 0.03, "RANGE": 0.0, "BEAR": -0.06}

    MIN_ADJUST_THRESHOLD = 0.05
    TARGET_CAP = 0.98
    TREND_CONTINUATION_BOOST = 0.06
    RECOVERY_MIN_STEP = 0.015
    BUY_COOLDOWN = {"BULL": 3, "RANGE": 5, "TRANSITION": 10, "BEAR": 36}
    EPISODE_MAX_CALLS = 180
    DEFENSE_MIN_RECOVERY_CALLS = 5
    RECOVERY_TEST_CALLS = 45
    FAILED_RECOVERY_CALLS = 55
    DISTRIBUTION_LOCK_CALLS = 24
    DISTRIBUTION_MIN_REENTRY_CALLS = 8
    DEEP_BASE_MIN_CALLS = 120
    DEEP_BASE_MIN_DRAWDOWN = 0.30
    DEEP_BASE_MIN_CURRENT_DISCOUNT = 0.12

    BEAR_BASE_CAP = {"BTC/USDT": 0.18, "ETH/USDT": 0.12, "BNB/USDT": 0.0, "SOL/USDT": 0.12}
    BEAR_BASE_DEFAULT_CAP = 0.0
    BEAR_BASE_BUDGET_FRACTION = 0.30
    BEAR_BASE_EXIT_MIN_HOLD_CALLS = 120
    TRANSITION_BUY_MAX_PCT = 0.08
    BEAR_BUY_MAX_PCT = 0.03
    LATE_TREND_CONT_MAX_BUY_PCT = 0.08
    ENABLE_LATE_TREND_SOFT_CAP = True
    COUNT_BEAR_BASE_BUYS_AS_EPISODE_RECOVERY = True

    USE_INDEPENDENT_BEAR_BASE_EXIT_SETUP = True
    RECOVERY_CONFIRM_MIN_BUDGET_RATIO = 0.50
    RECOVERY_OVERLAY_CAP = {"BTC/USDT": 0.12, "ETH/USDT": 0.12, "BNB/USDT": 0.08}
    RECOVERY_OVERLAY_PORTFOLIO_CAP = 0.25
    RECOVERY_OVERLAY_TOTAL_CAP = 1.20
    RECOVERY_OVERLAY_MIN_RAW = 0.15

    RECOVERY_CREDIT_ALLOWED_CLOSE_REASONS = {"recovery_signal_confirmed_budget_open", "expired"}
    RECOVERY_CREDIT_SYMBOL_CAP = 0.30
    RECOVERY_CREDIT_PORTFOLIO_AVG_CAP = 0.18
    RECOVERY_CREDIT_DECAY_CALLS = 180
    RECOVERY_CREDIT_DECAY_FRACTION = 0.25
    RECOVERY_CREDIT_DROP_MIN = {"BTC/USDT": 0.04, "ETH/USDT": 0.02, "BNB/USDT": 0.02}
    RECOVERY_CREDIT_ROLLING_POS_MAX = {"BTC/USDT": 0.55, "ETH/USDT": 0.62, "BNB/USDT": 0.62}
    RECOVERY_CREDIT_DONCHIAN_POS_MAX = {"BTC/USDT": 0.60, "ETH/USDT": 0.68, "BNB/USDT": 0.68}
    RECOVERY_CREDIT_RELEASE_CAP = {"BTC/USDT": 0.04, "ETH/USDT": 0.05, "BNB/USDT": 0.04}
    RECOVERY_CREDIT_CONSUME_MAIN_BUY_SET = {"value-recovery", "recovery-probe-buy"}
    RECOVERY_CREDIT_CONSUME_LOOKBACK_CALLS = 8
    RECOVERY_CREDIT_BTC_DEEP_DROP_MIN = 0.25
    RECOVERY_CREDIT_BTC_DEEP_RELEASE_CAP = 0.04
    RECOVERY_CREDIT_BTC_DEEP_LOOKBACK_CALLS = 8

    OPPORTUNITY_FLOOR_SYMBOLS = {"ETH/USDT", "BNB/USDT"}
    OPPORTUNITY_FLOOR_TARGET = {"ETH/USDT": 0.08, "BNB/USDT": 0.08}
    OPPORTUNITY_FLOOR_MAX_BUY_PCT = 0.02
    OPPORTUNITY_FLOOR_COOLDOWN_CALLS = 18

    PROTECTED_FLOOR_STOP_LOSS_PCT = 0.30
    PROTECTED_FLOOR_TAKE_PROFIT_PCT = 0.80
    PROTECTED_FLOOR_HIGH_ROLLING_POS = 0.75
    PROTECTED_FLOOR_HIGH_DONCHIAN_POS = 0.78
    PROTECTED_FLOOR_EXIT_MIN_HOLD_CALLS = 120
    PROTECTED_FLOOR_EXIT_PROFIT = 1.20
    PROTECTED_FLOOR_EXIT_REBOUND_PROFIT = 0.80
    PROTECTED_FLOOR_EXIT_FRACTION = 0.35
    PROTECTED_FLOOR_EXIT_MIN_NEW_HIGH = 0.18

    ENABLE_LIFECYCLE_LOW_BASE_BEHAVIOR = False
    ENABLE_LIFECYCLE_BASE_EXIT_BEHAVIOR = False
    LIFECYCLE_LOW_BASE_CAP = {"BTC/USDT": 0.0, "ETH/USDT": 0.0, "BNB/USDT": 0.0}
    LIFECYCLE_LOW_BASE_PORTFOLIO_CAP = 0.14
    LIFECYCLE_LOW_BASE_MAX_BUY_PCT = 0.02
    LIFECYCLE_LOW_BASE_COOLDOWN_CALLS = 45
    LIFECYCLE_BASE_EXIT_MIN_HOLD_CALLS = 90
    LIFECYCLE_BASE_EXIT_PROFIT_PCT = 0.75
    LIFECYCLE_BASE_EXIT_DISTRIBUTION_PROFIT_PCT = 0.45
    TOTAL_EXPOSURE_CAP = 1.00

    EXEC_LOW_AWARE_LOW_MULT = 2.60
    EXEC_LOW_AWARE_LOW_CAP = 2.00
    EXEC_LOW_AWARE_TREND_MULT = 1.75
    EXEC_LOW_AWARE_TREND_CAP = 1.75
    EXECUTION_TRANSFORM_BORROW_APR = 0.10
    EXECUTION_TRANSFORM_MIN_TARGET_GAP = 0.005
    EXECUTION_TRANSFORM_MIN_NOTIONAL = 5.0
    EXECUTION_TRANSFORM_MAINTENANCE_MARGIN = 0.25
    EXECUTION_TRANSFORM_WARNING_GROSS = 1.85
    EXECUTION_TRANSFORM_EVENT_TRIGGERED = True
    EXECUTION_TRANSFORM_EVENT_DRIFT_GAP = 0.10
    EXECUTION_TRANSFORM_INTRADAY_SHOCK_LADDER_V1 = True
    EXECUTION_TRANSFORM_INTRADAY_LADDER_MIN_POSITION = 0.80
    EXECUTION_TRANSFORM_INTRADAY_LADDER_FLOOR_POSITION = 0.80
    EXECUTION_TRANSFORM_INTRADAY_LADDER_MAX_POSITION = 2.70
    EXECUTION_TRANSFORM_INTRADAY_LADDER_SELL_DROP = -0.10
    EXECUTION_TRANSFORM_INTRADAY_LADDER_REDUCE_STEP = 0.35
    EXECUTION_TRANSFORM_INTRADAY_LADDER_ADD_DROP = -0.20
    EXECUTION_TRANSFORM_INTRADAY_LADDER_ADD_STEP = 0.20
    EXECUTION_TRANSFORM_INTRADAY_LADDER_RESTORE_DROP = -0.15
    EXECUTION_TRANSFORM_INTRADAY_LADDER_RESTORE_CLOSE = False
    EXECUTION_TRANSFORM_INTRADAY_LADDER_EXTRA_ADD_TIERS = [
        (-0.25, 0.20, "add_25"),
        (-0.30, 0.30, "add_30"),
    ]

    OUTER_OVERLAY_TARGET = {"BTC/USDT": 0.14, "ETH/USDT": 0.14, "BNB/USDT": 0.10}
    OUTER_OVERLAY_TOTAL_CAP = 1.20
    OUTER_MIN_RAW = 0.05
    OUTER_MIN_HOLD_CALLS = 120
    OUTER_HARD_STOP = 0.70
    OUTER_QTY_MULT = 2.0

    RECOVERY_ROUTE_MAX_ENTRY_MULTIPLE = 1.5
    BTC_TREND_CONT_EXPERIMENT = "off"

    ENABLE_ARCH_AUDIT = False
